#!/bin/bash

function setup_keys {
    if [ -z $SSH_AGENT_PID ]; then
        eval $(ssh-agent)
    fi

    ssh-add -t 3600 ~/.ssh/id_henrist
}

if [ -e ~/.ssh/id_henrist ]; then
    alias key='setup_keys'
fi

#if [ -e /usr/share/terminfo/x/xterm-256color ]; then
#        #export TERM='xterm-256color'
#        export TERM='screen-256color'
#else
#        export TERM='xterm-color'
#fi
